const menu = [
  {
    id: 1,
    title: "Assorted peppersoup",
    category: "appetizer",
    price: 2500,
    img: "./images/assortedpeppersoup.jpeg",
  },
  {
    id: 2,
    title: "Chicken and chips",
    category: "lunch",
    price: 4000,
    img: "./images/chickenandchips.jpeg",
  },
  {
    id: 3,
    title: "Classic afang",
    category: "lunch",
    price: 4000,
    img: "./images/classicafang.jpeg",
  },
  {
    id: 4,
    title: "Native soup",
    category: "lunch",
    price: 5000,
    img: "./images/nativesoup.jpeg",
  },
  {
    id: 5,
    title: "Ofada Stew and Rice",
    category: "lunch",
    price: 3000,
    img: "./images/ofadastewandrice.jpeg",
  },
  {
    id: 6,
    title: "Oriental Egusi",
    category: "lunch",
    price: 4000,
    img: "./images/oriental-egusi.jpeg",
  },
  {
    id: 7,
    title: "Seafood Okro",
    category: "lunch",
    price: 4000,
    img: "./images/seafood-okro.jpeg",
  },
  {
    id: 8,
    title: "Signature Jellof Rice",
    category: "lunch",
    price: 4000,
    img: "./images/signaturejellof.jpeg",
  },
  {
    id: 9,
    title: "Special Fried Rice ",
    category: "lunch",
    price: 4500,
    img: "./images/specialfriedrice.jpeg",
  },
  {
    id: 10,
    title: "Fruity Pancakes ",
    category: "breakfast",
    price: 2500,
    img: "./images/fruitypancakes.jpeg",
  },
  {
    id: 11,
    title: "Strawberry Milkshake ",
    category: "shakes",
    price: 3500,
    img: "./images/strawberrymilkshake.jpeg",
  },
  {
    id: 12,
    title: "Chocolate Milkshake ",
    category: "shakes",
    price: 3500,
    img: "./images/chocolatemilkshake.jpeg",
  },
  {
    id: 13,
    title: "Yam and Egg Sauce",
    category: "breakfast",
    price: 3500,
    img: "./images/yamandeggsauce.jpeg",
  },
  {
    id: 14,
    title: "Oreo Milkshake",
    category: "shakes",
    price: 3500,
    img: "./images/oreomilkshake.jpeg",
  },
  {
    id: 15,
    title: "Peppered Gizzard",
    category: "appetizer",
    price: 3500,
    img: "./images/gizzard.jpeg",
  },
];
export default menu;

